apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: devns
commonLabels:
  env: dev
replicas:
  - name: dov-deploy
    count: 1
images:
  - name: chukmunnlee/sk-dov-bear
    newTag: v6-beta

configMapGenerator:
  - name: dov-cm
    literals:
      - INSTANCE_NAME= "my dev bear"

patches:
  - target:
      kind: Ingress
      name: dov-ing
    path: patches.yaml