---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bgg-configmap
  namespace: bggns
data:
  BGG_DB_USER: root
  BGG_DB_HOST: bggdb-svc.bggns.svc.cluster.local
  index.html: | 
    <h1> Hello World </h1>
    <h1> Hello World </h1>
    <h1> Hello World </h1>
    
---
apiVersion: v1
kind: Secret
metadata:
  name: bgg-secret
  namespace: bggns
type: Opaque
data:
  BGG_DB_PASSWORD: Y2hhbmdlaXQ=  # Base64-encoded password "changeit"